apiVersion: apps/v1
kind: Deployment
metadata:
  name: demojava-deployment
  labels:
    app: demojava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demojava
  template:
    metadata:
      labels:
        app: demojava
    spec:
      containers:
      - name: demok8
        image: pn02cidocker/demo2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demojava-service
  labels:
    app: demojava
spec:
  type: LoadBalancer
  selector:
    app: demojava
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080